**CREATING A LOGISTIC REGRESSION TO PREDICT ABSEENTEEISM**

IMPORT THE RELEVANT LIBRARIES

In [14]:
import pandas as pd
import numpy as np

Load the data

In [15]:
data_preprocessed = pd.read_csv(r"C:\Users\DELL\Downloads\df_preprocessed.csv")

In [19]:
data_preprocessed

reason_1  reason_2  reason_3  reason_4        Date  \
0           0         0         0         1  2015-07-14   
1           0         0         0         0  2015-07-14   
2           0         0         0         1  2015-07-15   
3           1         0         0         0  2015-07-16   
4           0         0         0         1  2015-07-23   
..        ...       ...       ...       ...         ...   
694         1         0         0         0  2018-05-23   
695         1         0         0         0  2018-05-23   
696         1         0         0         0  2018-05-24   
697         0         0         0         1  2018-05-24   
698         0         0         0         1  2018-05-31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
694                     179                22   40                  237.656   
695                     225                26   28                  237.656   
696                     330                16   28                  237.656   
697                     235                16   32                  237.656   
698                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
694               22          1         2     0                          8   
695               24          0         1     2                          3   
696               25          1         0     0                          8   
697               25          1         0     0                          2   
698               25          0         1     1                          2   

     Month Value  Day of the week  
0              7                1  
1              7                1  
2              7                2  
3              7                3  
4              7                3  
..           ...              ...  
694            5                2  
695            5                2  
696            5                3  
697            5                3  
698            5                3  

[699 rows x 16 columns]

Create the targets

In [20]:
data_preprocessed["Absenteeism Time in Hours"].median()

3.0

In [21]:
targets = np.where(data_preprocessed["Absenteeism Time in Hours"] > 3,1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,

In [22]:
data_preprocessed["Excessive Absenteeism"] = targets

In [23]:
data_preprocessed.head()

reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-14                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [24]:
data_preprocessed["Excessive Absenteeism"].value_counts()

0    380
1    319
Name: Excessive Absenteeism, dtype: int64

A comment on the targets

In [10]:
targets.sum() / targets.shape[0]

0.4563662374821173

In [25]:
data_preprocessed

reason_1  reason_2  reason_3  reason_4        Date  \
0           0         0         0         1  2015-07-14   
1           0         0         0         0  2015-07-14   
2           0         0         0         1  2015-07-15   
3           1         0         0         0  2015-07-16   
4           0         0         0         1  2015-07-23   
..        ...       ...       ...       ...         ...   
694         1         0         0         0  2018-05-23   
695         1         0         0         0  2018-05-23   
696         1         0         0         0  2018-05-24   
697         0         0         0         1  2018-05-24   
698         0         0         0         1  2018-05-31   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
694                     179                22   40                  237.656   
695                     225                26   28                  237.656   
696                     330                16   28                  237.656   
697                     235                16   32                  237.656   
698                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                 30          0         2     1                          4   
1                 31          0         1     0                          0   
2                 31          0         0     0                          2   
3                 24          0         2     0                          4   
4                 30          0         2     1                          2   
..               ...        ...       ...   ...                        ...   
694               22          1         2     0                          8   
695               24          0         1     2                          3   
696               25          1         0     0                          8   
697               25          1         0     0                          2   
698               25          0         1     1                          2   

     Month Value  Day of the week  Excessive Absenteeism  
0              7                1                      1  
1              7                1                      0  
2              7                2                      0  
3              7                3                      1  
4              7                3                      0  
..           ...              ...                    ...  
694            5                2                      1  
695            5                2                      0  
696            5                3                      1  
697            5                3                      0  
698            5                3                      0  

[699 rows x 17 columns]

In [26]:
data_with_targets = data_preprocessed.drop(["Absenteeism Time in Hours",
                                            "Day of the week","Daily Work Load Average", "Distance to Work"], axis=1)

In [27]:
data_with_targets is data_preprocessed

False

In [28]:
data_with_targets.head()

reason_1  reason_2  reason_3  reason_4        Date  Transportation Expense  \
0         0         0         0         1  2015-07-14                     289   
1         0         0         0         0  2015-07-14                     118   
2         0         0         0         1  2015-07-15                     179   
3         1         0         0         0  2015-07-16                     279   
4         0         0         0         1  2015-07-23                     289   

   Age  Body Mass Index  Education  Children  Pets  Month Value  \
0   33               30          0         2     1            7   
1   50               31          0         1     0            7   
2   38               31          0         0     0            7   
3   39               24          0         2     0            7   
4   33               30          0         2     1            7   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [29]:
data_with_point = data_with_targets.drop(["Date"], axis = 1)

In [30]:
data_with_point

reason_1  reason_2  reason_3  reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
694         1         0         0         0                     179   40   
695         1         0         0         0                     225   28   
696         1         0         0         0                     330   28   
697         0         0         0         1                     235   32   
698         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  \
0                 30          0         2     1            7   
1                 31          0         1     0            7   
2                 31          0         0     0            7   
3                 24          0         2     0            7   
4                 30          0         2     1            7   
..               ...        ...       ...   ...          ...   
694               22          1         2     0            5   
695               24          0         1     2            5   
696               25          1         0     0            5   
697               25          1         0     0            5   
698               25          0         1     1            5   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
694                      1  
695                      0  
696                      1  
697                      0  
698                      0  

[699 rows x 12 columns]

In [31]:
data_with_targets = data_with_point

In [32]:
data_with_targets

reason_1  reason_2  reason_3  reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
694         1         0         0         0                     179   40   
695         1         0         0         0                     225   28   
696         1         0         0         0                     330   28   
697         0         0         0         1                     235   32   
698         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  \
0                 30          0         2     1            7   
1                 31          0         1     0            7   
2                 31          0         0     0            7   
3                 24          0         2     0            7   
4                 30          0         2     1            7   
..               ...        ...       ...   ...          ...   
694               22          1         2     0            5   
695               24          0         1     2            5   
696               25          1         0     0            5   
697               25          1         0     0            5   
698               25          0         1     1            5   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
694                      1  
695                      0  
696                      1  
697                      0  
698                      0  

[699 rows x 12 columns]

In [33]:
data_with_targets.columns

Index(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value', 'Excessive Absenteeism'],
      dtype='object')

In [20]:
data_with_target = data_with_targets.reindex(columns=['reason_1',
 'reason_2',
 'reason_3',
 'reason_4',
 'Month Value',                                
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Education',
 'Children',
 'Pets',
 'Excessive Absenteeism'])

In [36]:
data_with_targets

reason_1  reason_2  reason_3  reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
694         1         0         0         0                     179   40   
695         1         0         0         0                     225   28   
696         1         0         0         0                     330   28   
697         0         0         0         1                     235   32   
698         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  \
0                 30          0         2     1            7   
1                 31          0         1     0            7   
2                 31          0         0     0            7   
3                 24          0         2     0            7   
4                 30          0         2     1            7   
..               ...        ...       ...   ...          ...   
694               22          1         2     0            5   
695               24          0         1     2            5   
696               25          1         0     0            5   
697               25          1         0     0            5   
698               25          0         1     1            5   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
694                      1  
695                      0  
696                      1  
697                      0  
698                      0  

[699 rows x 12 columns]

SELECTING THE INPUT FOR REGRESSION

In [38]:
data_with_targets.shape

(699, 12)

In [23]:
data_with_target.iloc[:,0:-1]

reason_1  reason_2  reason_3  reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
694         1         0         0         0            5   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         0         0         0         1            5   
698         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
694                     179   40               22          1         2     0  
695                     225   28               24          0         1     2  
696                     330   28               25          1         0     0  
697                     235   32               25          1         0     0  
698                     291   40               25          0         1     1  

[699 rows x 11 columns]

In [40]:
unscaled_inputs = data_with_targets.iloc[:,0:-1]

In [41]:
unscaled_inputs

reason_1  reason_2  reason_3  reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
694         1         0         0         0                     179   40   
695         1         0         0         0                     225   28   
696         1         0         0         0                     330   28   
697         0         0         0         1                     235   32   
698         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
694               22          1         2     0            5  
695               24          0         1     2            5  
696               25          1         0     0            5  
697               25          1         0     0            5  
698               25          0         1     1            5  

[699 rows x 11 columns]

STANDARDIZE THE DATA

In [42]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [5]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
        def __init__(self,columns,copy=True,with_mean=True, with_std=True):
            self.columns= columns
            self.copy = copy
            self.with_mean = with_mean
            self.with_std = with_std
            
        def fit(self,X,y=None):
            self.scaler = StandardScaler(copy = self.copy, with_mean=self.with_mean, with_std=self.with_std)
            self.scaler.fit(X[self.columns],y)
            self.mean_ = np.mean(X[self.columns])
            self.var_ = np.var(X[self.columns])
            return self   
        
        def transform(self,X,y=None,copy=None):
            init_col_order = X.columns
            X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
            X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
            return pd.concat([X_not_scaled,X_scaled],axis=1)[init_col_order]
        

In [43]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [44]:
#columns_to_scale = ['Month Value','Day of the week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index',
       #'Children','Pets']
        
columns_to_omit =["reason_1", "reason_2", "reason_3", "reason_4","Eductaion"]

In [45]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [46]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [32]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Education', 'Children', 'Pets'])

In [48]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

AttributeError: 'CustomScaler' object has no attribute 'scaler'

In [51]:
scaled_inputs

NameError: name 'scaled_inputs' is not defined

In [37]:
scaled_inputs.shape

(699, 11)

SPLIT THE DATA INTO TRAIN & TEST AND SHUFFLE

In [38]:
from sklearn.model_selection import train_test_split

SPLIT

In [39]:
train_test_split(scaled_inputs,targets)

[     reason_1  reason_2  reason_3  reason_4  Month Value  \
 447         0         0         0         1     1.527333   
 213         0         0         0         0    -0.567185   
 636         1         0         0         0    -1.165619   
 314         1         0         0         0     0.928899   
 301         0         0         0         1     0.928899   
 ..        ...       ...       ...       ...          ...   
 236         1         0         0         0    -0.267968   
 283         0         0         0         1     0.629682   
 9           0         0         0         1     0.031249   
 602         1         0         0         0    -1.464836   
 606         0         0         0         1    -1.464836   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 447               -0.654811  0.248498         1.004073  -0.448365 -0.920243   
 213                1.622968 -1.319194        -0.407147   2.230327 -0.920243   
 636                0.0390

In [40]:
 x_train,x_test,y_train,y_test = train_test_split(scaled_inputs, targets,train_size = 0.8,random_state =15)

In [41]:
print(x_train.shape, y_train.shape)

(559, 11) (559,)


In [42]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


LOGISTIC REGRESSION WITH SKLEARN

In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [69]:
reg = LogisticRegression()

In [70]:
reg.fit(x_train, y_train)

LogisticRegression()

In [71]:
reg.score(x_train,y_train)

0.776386404293381

MANUALLY CHECK THE ACCURACY

In [72]:
model_output = reg.predict(x_train)
model_output

array([0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,

In [73]:
y_train

array([0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,

In [74]:
model_output == y_train

array([ True, False,  True,  True, False, False, False,  True,  True,
        True, False,  True,  True,  True, False,  True,  True, False,
        True, False,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True, False,  True,
        True, False, False,  True,  True,  True, False,  True,  True,
        True, False, False, False,  True, False,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True, False, False,  True, False,  True,
        True, False,  True,  True, False,  True,  True, False,  True,
       False,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,

In [75]:
np.sum((model_output == y_train))

434

In [76]:
model_output.shape[0]

559

In [77]:
np.sum((model_output == y_train)) / model_output.shape[0]

0.776386404293381

 FINDING THE INTERCEPT AND COEFFICIENTS

In [78]:
reg.intercept_

array([-1.67952233])

In [79]:
reg.coef_

array([[ 2.90657085e+00,  6.72219922e-01,  2.92306538e+00,
         8.03914288e-01,  1.28750627e-03,  6.30271446e-01,
        -1.74681033e-01,  2.98320758e-01,  2.77722221e-04,
         4.59469338e-01, -2.64209939e-01]])

In [80]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [81]:
feature_name = unscaled_inputs.columns.values

In [82]:
summary_table = pd.DataFrame(columns=["feature_name"], data = feature_name)
summary_table["Coefficient"]= np.transpose(reg.coef_)
summary_table

feature_name  Coefficient
0                 reason_1     2.906571
1                 reason_2     0.672220
2                 reason_3     2.923065
3                 reason_4     0.803914
4              Month Value     0.001288
5   Transportation Expense     0.630271
6                      Age    -0.174681
7          Body Mass Index     0.298321
8                Education     0.000278
9                 Children     0.459469
10                    Pets    -0.264210

In [83]:
summary_table.index =summary_table.index + 1
summary_table.loc[0] = ["Intercept", reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

feature_name  Coefficient
0                Intercept    -1.679522
1                 reason_1     2.906571
2                 reason_2     0.672220
3                 reason_3     2.923065
4                 reason_4     0.803914
5              Month Value     0.001288
6   Transportation Expense     0.630271
7                      Age    -0.174681
8          Body Mass Index     0.298321
9                Education     0.000278
10                Children     0.459469
11                    Pets    -0.264210

INTERPRETING THE COEFFICIENTS

In [84]:
summary_table["Odds_ratio"] = np.exp(summary_table.Coefficient)

In [85]:
summary_table

feature_name  Coefficient  Odds_ratio
0                Intercept    -1.679522    0.186463
1                 reason_1     2.906571   18.293958
2                 reason_2     0.672220    1.958580
3                 reason_3     2.923065   18.598211
4                 reason_4     0.803914    2.234269
5              Month Value     0.001288    1.001288
6   Transportation Expense     0.630271    1.878120
7                      Age    -0.174681    0.839725
8          Body Mass Index     0.298321    1.347594
9                Education     0.000278    1.000278
10                Children     0.459469    1.583234
11                    Pets    -0.264210    0.767812

In [86]:
summary_table.sort_values("Odds_ratio",ascending = False)

feature_name  Coefficient  Odds_ratio
3                 reason_3     2.923065   18.598211
1                 reason_1     2.906571   18.293958
4                 reason_4     0.803914    2.234269
2                 reason_2     0.672220    1.958580
6   Transportation Expense     0.630271    1.878120
10                Children     0.459469    1.583234
8          Body Mass Index     0.298321    1.347594
5              Month Value     0.001288    1.001288
9                Education     0.000278    1.000278
7                      Age    -0.174681    0.839725
11                    Pets    -0.264210    0.767812
0                Intercept    -1.679522    0.186463

TESTING THE MACHINE LEARNING MODEL

In [87]:
reg.score(x_test,y_test)

0.7142857142857143

In [88]:
predict_proba = reg.predict_proba(x_test)

In [89]:
predict_proba

array([[0.35018439, 0.64981561],
       [0.45517086, 0.54482914],
       [0.78595035, 0.21404965],
       [0.38912193, 0.61087807],
       [0.39843819, 0.60156181],
       [0.76088825, 0.23911175],
       [0.88717558, 0.11282442],
       [0.51680461, 0.48319539],
       [0.55433033, 0.44566967],
       [0.78601515, 0.21398485],
       [0.75387918, 0.24612082],
       [0.87219928, 0.12780072],
       [0.4857686 , 0.5142314 ],
       [0.75387918, 0.24612082],
       [0.34992144, 0.65007856],
       [0.87249957, 0.12750043],
       [0.75359315, 0.24640685],
       [0.13183175, 0.86816825],
       [0.074812  , 0.925188  ],
       [0.55509159, 0.44490841],
       [0.3980689 , 0.6019311 ],
       [0.78562612, 0.21437388],
       [0.35062284, 0.64937716],
       [0.34983382, 0.65016618],
       [0.34992144, 0.65007856],
       [0.13218488, 0.86781512],
       [0.8043833 , 0.1956167 ],
       [0.85741271, 0.14258729],
       [0.88702124, 0.11297876],
       [0.26914377, 0.73085623],
       [0.

In [90]:
predict_proba.shape

(140, 2)

In [91]:
predict_proba[:,-1]

array([0.64981561, 0.54482914, 0.21404965, 0.61087807, 0.60156181,
       0.23911175, 0.11282442, 0.48319539, 0.44566967, 0.21398485,
       0.24612082, 0.12780072, 0.5142314 , 0.24612082, 0.65007856,
       0.12750043, 0.24640685, 0.86816825, 0.925188  , 0.44490841,
       0.6019311 , 0.21437388, 0.64937716, 0.65016618, 0.65007856,
       0.86781512, 0.1956167 , 0.14258729, 0.11297876, 0.73085623,
       0.21404965, 0.89023169, 0.8678593 , 0.55166244, 0.48309919,
       0.7969756 , 0.51030278, 0.50982142, 0.21456859, 0.11290156,
       0.72805722, 0.72374936, 0.21398485, 0.24604935, 0.50050673,
       0.9263217 , 0.21392006, 0.12784367, 0.24654995, 0.2464784 ,
       0.21398485, 0.11297876, 0.36040787, 0.28119234, 0.7274466 ,
       0.51049531, 0.30970429, 0.72767568, 0.24633532, 0.50060304,
       0.21463352, 0.21392006, 0.67097304, 0.75194648, 0.24640685,
       0.24597789, 0.1425402 , 0.6939105 , 0.24626381, 0.21398485,
       0.37242895, 0.57675395, 0.40380736, 0.11290156, 0.54568

SAVE THE MODEL

In [98]:
import pickle

In [104]:
with open("model_pickle","wb" ) as file:
        pickle.dump(reg,file)

In [97]:
with open("scaler","wb") as file:
         pickle.dump( absenteeism_scaler,file)